import 'package:battleship/models/field_item.dart';

List<List<FieldItem>> playingField1 = [
  [
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
  ],
  [
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
  ],
  [
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
  ],
  [
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
  ],
  [
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
  ],
  [
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
  ],
  [
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
  ],
];

List<List<FieldItem>> playingField1Hidden = [
  [
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
  ],
  [
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
  ],
  [
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
  ],
  [
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
  ],
  [
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
  ],
  [
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
  ],
  [
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
  ],
];

List<List<FieldItem>> playingField2 = [
  [
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
  ],
  [
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
  ],
  [
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
  ],
  [
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
  ],
  [
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
  ],
  [
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
  ],
  [
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
  ],
];

List<List<FieldItem>> playingField2Hidden = [
  [
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
  ],
  [
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
  ],
  [
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
  ],
  [
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
  ],
  [
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
  ],
  [
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
  ],
  [
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
    FieldItem(false, false, false),
  ],
];

void clearField1() {
  playingField1 = [
    [
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
    ],
    [
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
    ],
    [
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
    ],
    [
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
    ],
    [
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
    ],
    [
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
    ],
    [
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
    ],
  ];
}

void clearField2() {
  playingField2 = [
    [
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
    ],
    [
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
    ],
    [
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
    ],
    [
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
    ],
    [
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
    ],
    [
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
    ],
    [
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
    ],
  ];
}

void clearField1Hidden() {
  playingField1Hidden = [
    [
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
    ],
    [
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
    ],
    [
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
    ],
    [
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
    ],
    [
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
    ],
    [
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
    ],
    [
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
    ],
  ];
}

void clearField2Hidden() {
  playingField2Hidden = [
    [
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
    ],
    [
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
    ],
    [
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
    ],
    [
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
    ],
    [
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
    ],
    [
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
    ],
    [
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
      FieldItem(false, false, false),
    ],
  ];
}
