import 'package:knighthood/models/tile_object.dart';

// Карты
List<List<TileObject>> map1 = [
  [
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
  ],
  [
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
  ],
  [
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
  ],
  [
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
  ],
  [
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
  ],
  [
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
  ],
  [
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
  ],
  [
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
  ],
  [
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
  ],
  [
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
    TileObject(true, false, false),
  ],
];

// Функции генерации карт
void generateMap1() {
  map1[1][2].isFree = false;
  map1[1][2].isWall = true;
}
