import 'package:knighthood/models/tile_object.dart';

List<List<TileObject>> map1 = [
  [
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
  ],
  [
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
  ],
  [
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
  ],
  [
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
  ],
  [
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
  ],
  [
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
  ],
  [
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
  ],
  [
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
  ],
  [
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
  ],
  [
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
    TileObject(false, false, false),
  ],
];
